/**
 * ExportSystem.ts
 * A lightweight, offline-first print/PDF document generator.
 * Injects a hidden iframe, loads the formatted document content with printable stylesheets,
 * and launches the browser's print dialog to save as PDF.
 */

export interface PrintableDocPayload {
  title: string;
  subtitle?: string;
  metadata: { label: string; value: string | number }[];
  htmlContent: string;
}

export const exportDocumentToPDF = (
  payload: PrintableDocPayload,
  onLogExport: (module: string, title: string) => void,
  moduleName: string
) => {
  const { title, subtitle, metadata, htmlContent } = payload;

  // 1. Create printable HTML structure
  const metadataHtml = metadata
    .map(
      (item) => `
      <div style="flex: 1; min-width: 150px; margin-bottom: 8px;">
        <span style="font-size: 10px; font-weight: 800; text-transform: uppercase; color: #64748b; display: block; tracking-widest: 0.05em;">${item.label}</span>
        <span style="font-size: 13px; font-weight: 700; color: #1e293b;">${item.value}</span>
      </div>
    `
    )
    .join('');

  const docHtml = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;800&family=Inter:wght@400;500;700&display=swap');
          
          body {
            font-family: 'Inter', sans-serif;
            color: #1e293b;
            background: #ffffff;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
          }
          
          h1, h2, h3, h4, h5 {
            font-family: 'Outfit', sans-serif;
            color: #0f172a;
            margin-top: 0;
          }
          
          h1 {
            font-size: 26px;
            font-weight: 800;
            margin-bottom: 4px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 12px;
          }

          .subtitle {
            font-size: 14px;
            font-weight: 600;
            color: #4f46e5;
            margin-bottom: 20px;
          }
          
          .meta-container {
            display: flex;
            flex-wrap: wrap;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 16px;
            border-radius: 12px;
            margin-bottom: 30px;
          }

          .content-area {
            font-size: 13px;
          }

          .content-area ul {
            padding-left: 20px;
          }

          .content-area li {
            margin-bottom: 6px;
          }
          
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 16px;
            text-align: center;
            font-size: 10px;
            color: #94a3b8;
            font-weight: 500;
          }

          @media print {
            body {
              padding: 20px;
            }
            .no-print {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        <div>
          <h1>${title}</h1>
          ${subtitle ? `<div class="subtitle">${subtitle}</div>` : ''}
          
          <div class="meta-container">
            ${metadataHtml}
          </div>

          <div class="content-area">
            ${htmlContent}
          </div>

          <div class="footer">
            Generated by Engineering Student Assistant Workspace on ${new Date().toLocaleDateString()}
          </div>
        </div>
      </body>
    </html>
  `;

  // 2. Inject Iframe for clean print
  let iframe = document.getElementById('esa-print-iframe') as HTMLIFrameElement;
  if (!iframe) {
    iframe = document.createElement('iframe') as HTMLIFrameElement;
    iframe.id = 'esa-print-iframe';
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);
  }

  const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
  if (iframeDoc) {
    iframeDoc.open();
    iframeDoc.write(docHtml);
    iframeDoc.close();

    // Log the export event in analytics context
    onLogExport(moduleName, title);

    // Call print window
    setTimeout(() => {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
    }, 500);
  }
};
